- name: Deploy to Deta

  on:
    release:
      types: [published]

  jobs:
    deploy:
      uses: BogDAAAMN/deta-deploy-action@v1.0.1
      with:
        deta-access-token: ${{ secrets.DETA_ACCESS_TOKEN }}
        deta-name: web
        deta-project: pdfpad
        deta-project-dir: web
